import Navbar from '@/components/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/components/Footer'
import AuthProvider from '@/components/AuthProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'NMDB | v2',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>

      <body className={`${inter.className} antialiased min-h-screen overflow-x-hidden flex flex-col justify-between`}>
        <AuthProvider>
        <Navbar />
        <main className='mx-auto container'>
        {children}
        <Footer/>
        </main>
    
        </AuthProvider>
      </body>
    </html>
  );
}
